### ISSUE TITLE
Brackets not working?

### ISSUE THREAD

**Issue by danielepolencic** [kriomant/ch57x-keyboard-tool#11]
I have the following test config:

```
layers:
  - buttons:
      # Multimedia commands may be emitted. They cannot be mixed with
      # normal keyboard events and modifiers are not supported.
      - ["play"]
      - ["2"]
      - ["6"]
    knobs:
      - ccw: "cmd-shift-["
        press: "ctrl-q"
        cw: "cmd-shift-]"
```

Which fails validation with:

```
Error: load mapping config

Caused by:
    layers[0].knobs[0].ccw: error Alpha at: [ at line 35 column 14
```

I tried to replace the `[]` with codes (e.g. `cmd-shift-<219>`). The config validates, but the keys don't work.
What am I missing?

Thanks
