### ISSUE TITLE
Error: find USB device (1189:8890)

### ISSUE THREAD

**Issue by maurxce** [kriomant/ch57x-keyboard-tool#116]
Hey, first off, I really like this project, but unfortunately I have not gotten it to work yet :/

When I try to flash the example mapping (or a custom one) I get this error:
```
$ .\ch57x-keyboard-tool.exe upload .\test.yml
Error: find USB device

Caused by:
    0: get USB device list
    1: Other error
```
Defining the `vendor-id` (1189) and `product-id` (8890) explicitly did not help either (both int and hex).
My keypad is the 3x2 + 1 knob one

I used the latest release (1.5.0) and in case it's important - this is the config I tried flashing:
```yml
orientation: normal

rows: 2
columns: 3
knobs: 1

layers:
  - buttons:
      - ["f13", "f14", "f15"]
      - ["f16", "f17", "f18"]
    knobs:
      - ccw: "volumedown"
        press: "play" # possible to toggle between play and stop?
        cw: "volumeup"
```
