### ISSUE TITLE
How to map bacquote/tilde key?

### ISSUE THREAD

**Issue by pedjas** [kriomant/ch57x-keyboard-tool#43]
I want to send code for Alt+Ctrl+BackQuote key. BackQote is not on the list of keys.
Keyboard event viewer shows that code for that key is 192.

So I tried using key code 192 like

"alt-ctrl-<192>"

It does not work.

Is it possible to use this key combination?

It seems to me that I do not understand how to send proper decimal codes for keys as if I set any decimal key even for well known keys like a, enter, space or so, Keyboard Event Viewer shows completely different codes received, not those I sent, and not those i see when I pres those keys on standard keyboard.

key,  decimal code used,  code shown in keyboard event viewer
backquote, 192, 119
space, 32, 51
enter, 13, 74
a, 65, 119

So, maybe better question is what I am doing wrong?

```
orientation: normal

rows: 1
columns: 3
knobs: 1

layers:
  - buttons:
      - ["prev", "next", "alt-ctrl-<192>"]
    knobs:
      - ccw: "volumedown"
        press: 'mute'
        cw: "volumeup"

```
