### ISSUE TITLE
Upload command exits without error, but keyboard does not get new config

### ISSUE THREAD

**Issue by casidiablo** [kriomant/ch57x-keyboard-tool#74]
Initially I was getting hit by #50 

I was able to workaround it by any of these two methods:

- Using v1.2.4 on Windows
- Compiling myself including #69 (this I tried on Linux to see if the problem was my Windows)

In both cases, when executing the `upload` command, it seems to be doing something (because the command takes a few seconds to finish) but at the end of the day it does nothing. They keyboard does not actually emit the keys.

<details>
  <summary>config.yaml</summary>

```
orientation: normal

rows: 2
columns: 3
knobs: 1

layers:
  - buttons:
      - ["a", "ctrl-a", "b"]
      - ["e", "f", "g"]
    knobs:
      - ccw: "wheelup"
        press: "click"
        cw: "wheeldown"
  
  - buttons:
      - ["a", "ctrl-a", "b"]
      - ["e", "f", "g"]
    knobs:
      - ccw: "wheelup"
        press: "click"
        cw: "wheeldown"
  
  - buttons:
      - ["a", "ctrl-a", "b"]
      - ["e", "f", "g"]
    knobs:
      - ccw: "wheelup"
        press: "click"
        cw: "wheeldown"
```

</details>

I had to use the `--endpoint-address 2` flag (to be honest, I do not know what that is, I am just following the advice in #69), because otherwise I get this:

```
Error: single interrupt endpoint is expected, got:
EndpointDescriptor {
    bLength: 7,
    bDescriptorType: 5,
    bEndpointAddress: 130,
    bmAttributes: 3,
    wMaxPacketSize: 8,
    bInterval: 10,
}
EndpointDescriptor {
    bLength: 7,
    bDescriptorType: 5,
    bEndpointAddress: 2,
    bmAttributes: 3,
    wMaxPacketSize: 8,
    bInterval: 10,
}

You may try to choose one using --endpoint-address
```

I tried with the endpoint 130, but then I get a Windows popup saying a device is not recognized or something like that.

I also find it interesting that after disconnecting/connecting the keyboard, if I turn the knob it will launch this:

![image](https://github.com/kriomant/ch57x-keyboard-tool/assets/144458/6f86662f-10e5-4154-b4a5-2d1d83bc60ea)

By the way, they keyboard I have has 6 keys and 1 knob. Bought it on Temu but won't paste the link to it unless needed. This was the image in the listing:

![image](https://github.com/kriomant/ch57x-keyboard-tool/assets/144458/11ef2ec8-e258-4912-8113-cb1451588cd7)
