### ISSUE TITLE
Vendor: 0x1189 / Product 0x8840 /  layer 3 of 3 / CW is always mapped to "3" regardless config

### ISSUE THREAD

**Issue by djnzx** [kriomant/ch57x-keyboard-tool#96]
having such config
```
orientation: counterclockwise
rows: 2
columns: 3
knobs: 1

# layer 1:
layers:
  - buttons:
      - ["a", "b"]
      - ["c", "d"]
      - ["e", "f"]
    knobs:
      - cw: "1"
        press: "3"
        ccw: "2"

# layer 2
  - buttons:
      - ["g", "h"]
      - ["i", "j"]
      - ["k", "l"]
    knobs:
      - cw: "4"
        press: "6"
        ccw: "5"

# layer 3
  - buttons:
      - ["m", "n"]
      - ["o", "p"]
      - ["q", "r"]
    knobs:
      - cw: "7" # whatever you config, doesn't work, cw is always "3"
        press: "8"
        ccw: "9"
```
cw on layer 3 is always mapped to "3"
